USE Task_DB;

GO
IF NOT EXISTS(SELECT * FROM sysobjects WHERE name='Users')
CREATE TABLE Users
    (Id INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL ,
    Name VARCHAR(50) NOT NULL,
    Login VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    CreatedAt DATETIME,
    UpdatedAt DATETIME)

GO
IF NOT EXISTS(SELECT * FROM sysobjects WHERE name='Blogs')
CREATE TABLE Blogs
    (Id INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    UserId INTEGER FOREIGN KEY (UserId) REFERENCES USERS(Id) NOT NULL,
    Name VARCHAR(50),
    IsPaid BIT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME)

GO
IF NOT EXISTS(SELECT * FROM sysobjects WHERE name='Articles')
CREATE TABLE Articles
    (Id INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    BlogId INTEGER FOREIGN KEY (BlogId) REFERENCES Blogs(Id) NOT NULL,
    IsBlocked BIT NOT NULL,
    Content TEXT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME)
